language: python

python:
  - "3.7"

install:
  - pip install -r requirements.txt

script:
  - python epg_generator.py

deploy:
  provider: pages
  skip-cleanup: true
  local-dir: "output"
  github-token: $GITHUB_TOKEN
  on:
    branch: master