language: python

cache:
  pip: true
  directories:
    - cache/

env:
  global:
    - secure: "YPdT9/ix/BPt9Kx9mRuXruucXTYhHJzCZIwTAGhFv/VAM3BhHqwLVUi2pMEmqa8zbwqvbIXAwAKc9BI0dyox2mJwc1XP7TcHKIg/T2RWME8F+iKsdJQzysBY9JMQbYOLl0p34rrQK3RxAMLbRz9Tu0vHXk4xyQKEPN/OBMbZiyGtlFeoGPmA+A7Uat4x2pQCWVuLheXEnEE2GXEU5xQt3xe5Rer/03/8HYME6FHASUkfyZulPpGHmAgSwzaz6IGVX7zN8YAZE4mVn1Kw5Nybnxx0OE8obQKOhy6LEv73bRLfOoRsABe2E8cLrpo53kvFbZyH90H0N1WPNXd5Rbwtl95gUtHAQKk4H4FAZtpOeh3TxLr0KXARAPl8J8qDeD2kcT3YyntvMBJHh67lcnZcl5x0sjsM+Wved00K7+2MYKJwvdF7wALMwI7FXT2dJ+GB/t0ibZYTiWXPfoVuVBTDxLD7VrhOIXfxVMBO+xUGqjPpPHI0RQOGUexqKvQ9bx6oE1BH4eP9xpntx9AKwXEc3XD4TnABe785G/L/dtzaMKcSxXSnrFxwnzIqv2ocTniA9lKDooS20ziSeMqqX+gEgX1UssA4WKKYjY14PCciAp9137NzNQl7UTIG96GwgvmYahYM3QqL8AU9H9W4ASFpIQqjj3wrg0WjlyEKN3mM00s="

python:
  - "3.6"

install:
  - pip install -r requirements.txt

script:
  - python epg_generator.py

deploy:
  provider: pages
  skip-cleanup: true
  local-dir: "output"
  github-token: $GITHUB_TOKEN
  on:
    branch: master